insert into Habilidad (nombre_habilidad, descripcion) values ('Negociación', 'Toma de decisiones para resolver situaciones de manera oportuna');
insert into Habilidad (nombre_habilidad, descripcion) values ('Organización', 'Servicio al cliente para brindar una experiencia satisfactoria');
insert into Habilidad (nombre_habilidad, descripcion) values ('Servicio al cliente', 'Comunicación efectiva para transmitir información de manera clara');
insert into Habilidad (nombre_habilidad, descripcion) values ('Toma de decisiones', 'Negociación para alcanzar acuerdos beneficiosos');
insert into Habilidad (nombre_habilidad, descripcion) values ('Creatividad', 'Disciplina para mantener un rendimiento constante y responsable');
insert into Habilidad (nombre_habilidad, descripcion) values ('Supervisión', 'Negociación para alcanzar acuerdos beneficiosos');
insert into Habilidad (nombre_habilidad, descripcion) values ('Servicio al cliente', 'Atención al detalle para asegurar precisión en el trabajo');
insert into Habilidad (nombre_habilidad, descripcion) values ('Trabajo en equipo', 'Adaptabilidad para ajustarse a cambios en el entorno laboral');
insert into Habilidad (nombre_habilidad, descripcion) values ('Disciplina', 'Adaptabilidad para ajustarse a cambios en el entorno laboral');
insert into Habilidad (nombre_habilidad, descripcion) values ('Orientación a resultados', 'Trabajo en equipo para colaborar con colegas y lograr objetivos comunes');
insert into Habilidad (nombre_habilidad, descripcion) values ('Negociación', 'Resiliencia para manejar la presión en el trabajo');
insert into Habilidad (nombre_habilidad, descripcion) values ('Flexibilidad', 'Atención al detalle para asegurar precisión en el trabajo');
insert into Habilidad (nombre_habilidad, descripcion) values ('Control de calidad', 'Creatividad para aportar ideas innovadoras');
insert into Habilidad (nombre_habilidad, descripcion) values ('Resolución de problemas', 'Atención al detalle para asegurar precisión en el trabajo');
insert into Habilidad (nombre_habilidad, descripcion) values ('Servicio al cliente', 'Control de calidad para verificar que el trabajo se mantenga en altos niveles');
insert into Habilidad (nombre_habilidad, descripcion) values ('Trabajo en equipo', 'Orientación a resultados para enfocarse en cumplir objetivos');
insert into Habilidad (nombre_habilidad, descripcion) values ('Resolución de problemas', 'Resolución de problemas para encontrar soluciones a inconvenientes');
insert into Habilidad (nombre_habilidad, descripcion) values ('Control de calidad', 'Servicio al cliente para brindar una experiencia satisfactoria');
insert into Habilidad (nombre_habilidad, descripcion) values ('Adaptabilidad', 'Trabajo en equipo para colaborar con colegas y lograr objetivos comunes');
insert into Habilidad (nombre_habilidad, descripcion) values ('Resiliencia', 'Supervisión para garantizar el cumplimiento de estándares');
insert into Habilidad (nombre_habilidad, descripcion) values ('Resolución de problemas', 'Disciplina para mantener un rendimiento constante y responsable');
insert into Habilidad (nombre_habilidad, descripcion) values ('Toma de decisiones', 'Resolución de problemas para encontrar soluciones a inconvenientes');
insert into Habilidad (nombre_habilidad, descripcion) values ('Liderazgo', 'Trabajo en equipo para colaborar con colegas y lograr objetivos comunes');
insert into Habilidad (nombre_habilidad, descripcion) values ('Control de calidad', 'Capacidad de análisis para evaluar situaciones y tomar decisiones informadas');
insert into Habilidad (nombre_habilidad, descripcion) values ('Comunicación efectiva', 'Liderazgo para guiar y motivar al equipo');
insert into Habilidad (nombre_habilidad, descripcion) values ('Negociación', 'Control de calidad para verificar que el trabajo se mantenga en altos niveles');
insert into Habilidad (nombre_habilidad, descripcion) values ('Atención al detalle', 'Flexibilidad para adaptarse a diversas tareas');
insert into Habilidad (nombre_habilidad, descripcion) values ('Resolución de problemas', 'Negociación para alcanzar acuerdos beneficiosos');
insert into Habilidad (nombre_habilidad, descripcion) values ('Servicio al cliente', 'Servicio al cliente para brindar una experiencia satisfactoria');
insert into Habilidad (nombre_habilidad, descripcion) values ('Liderazgo', 'Flexibilidad para adaptarse a diversas tareas');
insert into Habilidad (nombre_habilidad, descripcion) values ('Adaptabilidad', 'Servicio al cliente para brindar una experiencia satisfactoria');
insert into Habilidad (nombre_habilidad, descripcion) values ('Trabajo en equipo', 'Organización para gestionar eficientemente las tareas diarias');
insert into Habilidad (nombre_habilidad, descripcion) values ('Supervisión', 'Comunicación efectiva para transmitir información de manera clara');
insert into Habilidad (nombre_habilidad, descripcion) values ('Capacidad de análisis', 'Trabajo en equipo para colaborar con colegas y lograr objetivos comunes');
insert into Habilidad (nombre_habilidad, descripcion) values ('Resolución de problemas', 'Servicio al cliente para brindar una experiencia satisfactoria');
insert into Habilidad (nombre_habilidad, descripcion) values ('Control de calidad', 'Supervisión para garantizar el cumplimiento de estándares');
insert into Habilidad (nombre_habilidad, descripcion) values ('Negociación', 'Toma de decisiones para resolver situaciones de manera oportuna');
insert into Habilidad (nombre_habilidad, descripcion) values ('Adaptabilidad', 'Orientación a resultados para enfocarse en cumplir objetivos');
insert into Habilidad (nombre_habilidad, descripcion) values ('Trabajo en equipo', 'Resiliencia para manejar la presión en el trabajo');
insert into Habilidad (nombre_habilidad, descripcion) values ('Capacidad de análisis', 'Supervisión para garantizar el cumplimiento de estándares');
insert into Habilidad (nombre_habilidad, descripcion) values ('Disciplina', 'Disciplina para mantener un rendimiento constante y responsable');
insert into Habilidad (nombre_habilidad, descripcion) values ('Gestión del tiempo', 'Supervisión para garantizar el cumplimiento de estándares');
insert into Habilidad (nombre_habilidad, descripcion) values ('Gestión del tiempo', 'Disciplina para mantener un rendimiento constante y responsable');
insert into Habilidad (nombre_habilidad, descripcion) values ('Gestión del tiempo', 'Orientación a resultados para enfocarse en cumplir objetivos');
insert into Habilidad (nombre_habilidad, descripcion) values ('Empatía', 'Resolución de problemas para encontrar soluciones a inconvenientes');
insert into Habilidad (nombre_habilidad, descripcion) values ('Trabajo en equipo', 'Negociación para alcanzar acuerdos beneficiosos');
insert into Habilidad (nombre_habilidad, descripcion) values ('Comunicación efectiva', 'Disciplina para mantener un rendimiento constante y responsable');
insert into Habilidad (nombre_habilidad, descripcion) values ('Orientación a resultados', 'Liderazgo para guiar y motivar al equipo');
insert into Habilidad (nombre_habilidad, descripcion) values ('Disciplina', 'Empatía para comprender y apoyar a otros');
insert into Habilidad (nombre_habilidad, descripcion) values ('Negociación', 'Organización para gestionar eficientemente las tareas diarias');
