insert into historial_laboral (empresa, cargo, duración, codigo_empleado) values ('Subway', 'ANFITRIÓN', 19, 32);
insert into historial_laboral (empresa, cargo, duración, codigo_empleado) values ('Carl''s Jr.', 'CAPITÁN DE MESEROS', 23, 35);
insert into historial_laboral (empresa, cargo, duración, codigo_empleado) values ('The Cheesecake Factory', 'ENCARGADO DE COMPRAS', 24, 60);
insert into historial_laboral (empresa, cargo, duración, codigo_empleado) values ('Taco Bell', 'SUBGERENTE DE COCINA', 19, 7);
insert into historial_laboral (empresa, cargo, duración, codigo_empleado) values ('IHOP', 'CAPACITADOR', 11, 84);
insert into historial_laboral (empresa, cargo, duración, codigo_empleado) values ('TGI Fridays', 'ANALISTA DE CALIDAD', 6, 40);
insert into historial_laboral (empresa, cargo, duración, codigo_empleado) values ('Chili''s', 'GERENTE DE MARKETING', 1, 50);
insert into historial_laboral (empresa, cargo, duración, codigo_empleado) values ('WingStreet', 'GERENTE DE COMPRAS', 3, 46);
insert into historial_laboral (empresa, cargo, duración, codigo_empleado) values ('Olive Garden', 'DIRECTOR DE RECURSOS HUMANOS', 13, 23);
insert into historial_laboral (empresa, cargo, duración, codigo_empleado) values ('Red Robin', 'GERENTE DE COMPRAS', 17, 7);
insert into historial_laboral (empresa, cargo, duración, codigo_empleado) values ('TGI Fridays', 'GERENTE DE COCINA', 18, 57);
insert into historial_laboral (empresa, cargo, duración, codigo_empleado) values ('Buffalo Wild Wings', 'CAPACITADOR', 16, 1);
insert into historial_laboral (empresa, cargo, duración, codigo_empleado) values ('Denny''s', 'ASISTENTE DE COCINA', 12, 34);
insert into historial_laboral (empresa, cargo, duración, codigo_empleado) values ('Papa John''s', 'DIRECTOR DE RECURSOS HUMANOS', 10, 64);
insert into historial_laboral (empresa, cargo, duración, codigo_empleado) values ('Qdoba Mexican Eats', 'GERENTE DE SERVICIO AL CLIENTE', 16, 35);
insert into historial_laboral (empresa, cargo, duración, codigo_empleado) values ('Denny''s', 'CAPACITADOR', 16, 32);
insert into historial_laboral (empresa, cargo, duración, codigo_empleado) values ('Pizza Hut', 'GERENTE DE ALMACÉN', 23, 41);
insert into historial_laboral (empresa, cargo, duración, codigo_empleado) values ('Outback Steakhouse', 'ANFITRIÓN', 7, 46);
insert into historial_laboral (empresa, cargo, duración, codigo_empleado) values ('Domino''s Pizza', 'GERENTE DE PISO', 1, 49);
insert into historial_laboral (empresa, cargo, duración, codigo_empleado) values ('Freddy''s Frozen Custard & Steakburgers', 'CAPACITADOR', 16, 100);
insert into historial_laboral (empresa, cargo, duración, codigo_empleado) values ('Freddy''s Frozen Custard & Steakburgers', 'GERENTE DE SERVICIO AL CLIENTE', 24, 89);
insert into historial_laboral (empresa, cargo, duración, codigo_empleado) values ('Outback Steakhouse', 'DIRECTOR FINANCIERO', 8, 43);
insert into historial_laboral (empresa, cargo, duración, codigo_empleado) values ('Boston Market', 'ALMACENERO', 6, 79);
insert into historial_laboral (empresa, cargo, duración, codigo_empleado) values ('Wingstop', 'AYUDANTE DE ALMACÉN', 23, 86);
insert into historial_laboral (empresa, cargo, duración, codigo_empleado) values ('Carl''s Jr.', 'RESPONSABLE DE MANTENIMIENTO', 3, 62);
insert into historial_laboral (empresa, cargo, duración, codigo_empleado) values ('KFC', 'ADMINISTRADOR DE REDES SOCIALES', 19, 72);
insert into historial_laboral (empresa, cargo, duración, codigo_empleado) values ('Sizzler', 'SOMMELIER', 18, 77);
insert into historial_laboral (empresa, cargo, duración, codigo_empleado) values ('TGI Fridays', 'ENCARGADO DE COMPRAS', 13, 95);
insert into historial_laboral (empresa, cargo, duración, codigo_empleado) values ('Jimmy John''s', 'DIRECTOR DE RECURSOS HUMANOS', 5, 39);
insert into historial_laboral (empresa, cargo, duración, codigo_empleado) values ('Dairy Queen', 'GERENTE DE MARKETING', 19, 13);
insert into historial_laboral (empresa, cargo, duración, codigo_empleado) values ('Chili''s', 'ANALISTA DE CALIDAD', 14, 53);
insert into historial_laboral (empresa, cargo, duración, codigo_empleado) values ('Chili''s', 'SUBGERENTE DE COCINA', 13, 64);
insert into historial_laboral (empresa, cargo, duración, codigo_empleado) values ('Olive Garden', 'AYUDANTE DE ALMACÉN', 16, 89);
insert into historial_laboral (empresa, cargo, duración, codigo_empleado) values ('Carl''s Jr.', 'ANFITRIÓN', 3, 69);
insert into historial_laboral (empresa, cargo, duración, codigo_empleado) values ('Five Guys', 'GERENTE DE OPERACIONES', 18, 54);
insert into historial_laboral (empresa, cargo, duración, codigo_empleado) values ('Applebee''s', 'ENCARGADO DE COMPRAS', 21, 62);
insert into historial_laboral (empresa, cargo, duración, codigo_empleado) values ('Carl''s Jr.', 'ENCARGADO DE EVENTOS', 10, 39);
insert into historial_laboral (empresa, cargo, duración, codigo_empleado) values ('Denny''s', 'GERENTE DE ALMACÉN', 3, 60);
insert into historial_laboral (empresa, cargo, duración, codigo_empleado) values ('Sizzler', 'ANALISTA DE CALIDAD', 22, 78);
insert into historial_laboral (empresa, cargo, duración, codigo_empleado) values ('Shake Shack', 'GERENTE DE COCINA', 4, 48);
insert into historial_laboral (empresa, cargo, duración, codigo_empleado) values ('Wingstop', 'CAPITÁN DE MESEROS', 22, 93);
insert into historial_laboral (empresa, cargo, duración, codigo_empleado) values ('Shake Shack', 'GERENTE DE OPERACIONES', 21, 82);
insert into historial_laboral (empresa, cargo, duración, codigo_empleado) values ('Wingstop', 'TÉCNICO DE MANTENIMIENTO', 13, 90);
insert into historial_laboral (empresa, cargo, duración, codigo_empleado) values ('Noodles & Company', 'DIRECTOR DE RECURSOS HUMANOS', 4, 14);
insert into historial_laboral (empresa, cargo, duración, codigo_empleado) values ('Buffalo Wild Wings', 'GERENTE DE OPERACIONES', 9, 23);
insert into historial_laboral (empresa, cargo, duración, codigo_empleado) values ('Jimmy John''s', 'CONTADOR', 10, 81);
insert into historial_laboral (empresa, cargo, duración, codigo_empleado) values ('Arby''s', 'CAPITÁN DE MESEROS', 13, 33);
insert into historial_laboral (empresa, cargo, duración, codigo_empleado) values ('Papa John''s', 'RECEPCIONISTA', 4, 17);
insert into historial_laboral (empresa, cargo, duración, codigo_empleado) values ('Applebee''s', 'GERENTE DE ALMACÉN', 20, 38);
insert into historial_laboral (empresa, cargo, duración, codigo_empleado) values ('Pizza Hut', 'LAVAPLATOS', 12, 71);
insert into historial_laboral (empresa, cargo, duración, codigo_empleado) values ('Pei Wei Asian Diner', 'SEGURIDAD', 23, 26);
insert into historial_laboral (empresa, cargo, duración, codigo_empleado) values ('Shake Shack', 'GERENTE GENERAL', 1, 27);
insert into historial_laboral (empresa, cargo, duración, codigo_empleado) values ('Pei Wei Asian Diner', 'GERENTE DE ALMACÉN', 16, 36);
insert into historial_laboral (empresa, cargo, duración, codigo_empleado) values ('TGI Fridays', 'GERENTE DE ALMACÉN', 19, 4);
insert into historial_laboral (empresa, cargo, duración, codigo_empleado) values ('Dairy Queen', 'ANFITRIÓN', 18, 72);
insert into historial_laboral (empresa, cargo, duración, codigo_empleado) values ('Freddy''s Frozen Custard & Steakburgers', 'GERENTE DE OPERACIONES', 8, 33);
insert into historial_laboral (empresa, cargo, duración, codigo_empleado) values ('Denny''s', 'LIMPIEZA', 2, 66);
insert into historial_laboral (empresa, cargo, duración, codigo_empleado) values ('Qdoba Mexican Eats', 'DIRECTOR DE RECURSOS HUMANOS', 24, 96);
insert into historial_laboral (empresa, cargo, duración, codigo_empleado) values ('Jimmy John''s', 'GERENTE DE PISO', 5, 85);
insert into historial_laboral (empresa, cargo, duración, codigo_empleado) values ('Cracker Barrel', 'AYUDANTE DE ALMACÉN', 8, 56);
insert into historial_laboral (empresa, cargo, duración, codigo_empleado) values ('Arby''s', 'RESPONSABLE DE MANTENIMIENTO', 17, 3);
insert into historial_laboral (empresa, cargo, duración, codigo_empleado) values ('Qdoba Mexican Eats', 'SUBGERENTE DE COCINA', 15, 72);
insert into historial_laboral (empresa, cargo, duración, codigo_empleado) values ('The Cheesecake Factory', 'MESERO', 10, 49);
insert into historial_laboral (empresa, cargo, duración, codigo_empleado) values ('Wingstop', 'ENCARGADO DE EVENTOS', 10, 2);
insert into historial_laboral (empresa, cargo, duración, codigo_empleado) values ('TGI Fridays', 'CONTADOR', 6, 64);
insert into historial_laboral (empresa, cargo, duración, codigo_empleado) values ('The Cheesecake Factory', 'ANALISTA DE CALIDAD', 1, 87);
insert into historial_laboral (empresa, cargo, duración, codigo_empleado) values ('Olive Garden', 'COCINERO', 1, 41);
insert into historial_laboral (empresa, cargo, duración, codigo_empleado) values ('Freddy''s Frozen Custard & Steakburgers', 'RESPONSABLE DE MANTENIMIENTO', 14, 83);
insert into historial_laboral (empresa, cargo, duración, codigo_empleado) values ('Outback Steakhouse', 'ADMINISTRADOR DE REDES SOCIALES', 8, 28);
insert into historial_laboral (empresa, cargo, duración, codigo_empleado) values ('Hardee''s', 'ASISTENTE DE COCINA', 1, 79);
insert into historial_laboral (empresa, cargo, duración, codigo_empleado) values ('Panera Bread', 'CAPITÁN DE MESEROS', 16, 71);
insert into historial_laboral (empresa, cargo, duración, codigo_empleado) values ('Red Robin', 'GERENTE DE COCINA', 8, 42);
insert into historial_laboral (empresa, cargo, duración, codigo_empleado) values ('Five Guys', 'ASISTENTE DE COCINA', 11, 1);
insert into historial_laboral (empresa, cargo, duración, codigo_empleado) values ('Pizza Hut', 'ANFITRIÓN', 16, 94);
insert into historial_laboral (empresa, cargo, duración, codigo_empleado) values ('Chili''s', 'ENCARGADO DE EVENTOS', 1, 50);
insert into historial_laboral (empresa, cargo, duración, codigo_empleado) values ('Denny''s', 'ALMACENERO', 11, 38);
insert into historial_laboral (empresa, cargo, duración, codigo_empleado) values ('Red Robin', 'ANALISTA DE CALIDAD', 14, 69);
insert into historial_laboral (empresa, cargo, duración, codigo_empleado) values ('Noodles & Company', 'SOMMELIER', 3, 33);
insert into historial_laboral (empresa, cargo, duración, codigo_empleado) values ('Carl''s Jr.', 'CAPACITADOR', 6, 59);
insert into historial_laboral (empresa, cargo, duración, codigo_empleado) values ('Dairy Queen', 'GERENTE DE SERVICIO AL CLIENTE', 23, 51);
insert into historial_laboral (empresa, cargo, duración, codigo_empleado) values ('Red Robin', 'SOMMELIER', 15, 50);
insert into historial_laboral (empresa, cargo, duración, codigo_empleado) values ('Arby''s', 'CAPITÁN DE MESEROS', 10, 17);
insert into historial_laboral (empresa, cargo, duración, codigo_empleado) values ('Hardee''s', 'GERENTE DE SERVICIO AL CLIENTE', 12, 79);
insert into historial_laboral (empresa, cargo, duración, codigo_empleado) values ('KFC', 'GERENTE DE OPERACIONES', 20, 40);
insert into historial_laboral (empresa, cargo, duración, codigo_empleado) values ('WingStreet', 'CAPACITADOR', 7, 66);
insert into historial_laboral (empresa, cargo, duración, codigo_empleado) values ('Dairy Queen', 'GERENTE DE PISO', 13, 7);
insert into historial_laboral (empresa, cargo, duración, codigo_empleado) values ('Panera Bread', 'CHEF PASTELERO', 2, 42);
insert into historial_laboral (empresa, cargo, duración, codigo_empleado) values ('Taco Bell', 'MESERO', 11, 76);
insert into historial_laboral (empresa, cargo, duración, codigo_empleado) values ('Jimmy John''s', 'BARTENDER', 23, 23);
insert into historial_laboral (empresa, cargo, duración, codigo_empleado) values ('Pizza Hut', 'DIRECTOR DE RECURSOS HUMANOS', 7, 89);
insert into historial_laboral (empresa, cargo, duración, codigo_empleado) values ('Olive Garden', 'ASISTENTE DE COCINA', 6, 80);
insert into historial_laboral (empresa, cargo, duración, codigo_empleado) values ('Pei Wei Asian Diner', 'SEGURIDAD', 14, 43);
insert into historial_laboral (empresa, cargo, duración, codigo_empleado) values ('Pei Wei Asian Diner', 'GERENTE DE SERVICIO AL CLIENTE', 9, 8);
insert into historial_laboral (empresa, cargo, duración, codigo_empleado) values ('The Cheesecake Factory', 'ADMINISTRADOR DE REDES SOCIALES', 22, 28);
insert into historial_laboral (empresa, cargo, duración, codigo_empleado) values ('Subway', 'ANFITRIÓN', 15, 47);
insert into historial_laboral (empresa, cargo, duración, codigo_empleado) values ('Olive Garden', 'GERENTE DE MARKETING', 11, 12);
insert into historial_laboral (empresa, cargo, duración, codigo_empleado) values ('The Cheesecake Factory', 'SOMMELIER', 20, 39);
insert into historial_laboral (empresa, cargo, duración, codigo_empleado) values ('Olive Garden', 'GERENTE DE COMPRAS', 5, 68);
insert into historial_laboral (empresa, cargo, duración, codigo_empleado) values ('Carl''s Jr.', 'GERENTE DE PISO', 24, 71);
insert into historial_laboral (empresa, cargo, duración, codigo_empleado) values ('Jimmy John''s', 'ENCARGADO DE EVENTOS', 8, 96);
